### ISSUE TITLE
Fetch token information from contracts instead of token metadata api.

### ISSUE THREAD

**Issue by talhasch** [Trust-Machines/multisafe-ui#19]
We need a way to read fungible token metadata (name, symbol, decimals) directly from token contracts instead of stacks api since FT metadata processing is disabled on testnet.

Contract source parsing instead of contract calls can be considered in terms of reading data faster.

**Comment by talhasch** [comment]
@wbnns @perplexedpigmy a fix for this ready here: #20  and preview available at https://multisafe-ui-git-token-reading-improvements-multisafe.vercel.app/ Could you test your testnet safe on it?

**Comment by perplexedpigmy** [comment]
@talhasch Tested,  and looking good, thanks for the quick fix.
any idea when it will be merged?

**Comment by talhasch** [comment]
@perplexedpigmy just merged
