### ISSUE TITLE
When connecting the wallet automatically pull the list of safe I am in

### ISSUE THREAD

**Issue by pradel** [Trust-Machines/multisafe-ui#5]
When I connect my wallet to the UI, I would like the UI to pull all the safes I am in, that way when I am using a new browser I can quickly open any safe without having to manually find the address.
The recent safe option is working only if you use the same browser (or maybe save this in Gaia?).

**Comment by talhasch** [comment]
Hey @pradel !

This is already in our todo list and currently we are building a backend for this. Once it ready we'll fetch safe list from the backend and remove local storage usage for saving safe list.

**Comment by talhasch** [comment]
This feature now implemented on the MultiSafe app homepage. Once you connect your wallet you see list of safes created by you or have you as one of its owners.
