### ISSUE TITLE
When deposit an asset, show balance and add max button

### ISSUE THREAD

**Issue by pradel** [Trust-Machines/multisafe-ui#6]
When I deposit an asset it would be great to see my balance and get a "max" button that fills the input automatically. Similar to how Alex is doing.

![Screenshot 2022-09-13 at 11 39 36](https://user-images.githubusercontent.com/5749437/189867992-fb32a4cb-976a-479e-aee1-d0805cc1f33d.png)
![Screenshot 2022-09-13 at 11 40 19](https://user-images.githubusercontent.com/5749437/189868169-46869b72-669c-474e-94f0-123a5ec5a382.png)

**Comment by talhasch** [comment]
We'll definitely have this!

**Comment by talhasch** [comment]
#25 added this feature
