### ISSUE TITLE
When deposit an NFT, automatically detect the ones in my wallet

### ISSUE THREAD

**Issue by pradel** [Trust-Machines/multisafe-ui#7]
When I deposit an NFT it would be great to automatically detect the NFTs in my wallet from the collection and get a list view with an image preview to select them as I don't know the IDs without having to look at my wallet in Gamma. Maybe Gamma API can be used for this feature?

![Screenshot 2022-09-13 at 11 42 16](https://user-images.githubusercontent.com/5749437/189868605-77d2f381-41c4-44e1-9dec-454cb133d296.png)

**Comment by talhasch** [comment]
This would be a nice and useful feature. Let's see what data source we can use for it.

**Comment by talhasch** [comment]
#26 added this feature. NFT holdings appears under the input and clicking on them autofills the input.

<img width="734" alt="Screenshot 2023-01-05 at 10 31 52" src="https://user-images.githubusercontent.com/1177676/210725908-fe9e2b73-659a-4966-a91a-388208cbc2d6.png">
