### ISSUE TITLE
What is happening when removing the only owner of the vault?

### ISSUE THREAD

**Issue by pradel** [Trust-Machines/multisafe-ui#9]
If there is only one owner in the safe, I can currently remove it, maybe the action should be removed from the UI?

![Screenshot 2022-09-13 at 11 46 58](https://user-images.githubusercontent.com/5749437/189869868-682e51d7-6e95-4949-a036-8f52378c2850.png)

**Comment by talhasch** [comment]
The safe must have at least 1 owner. This is a rule on the smart contract level. But, yes we can hide the delete button if there's only one owner

**Comment by talhasch** [comment]
#24 hides delete button if there is only 1 owner.
